-- phpMyAdmin SQL Dump
-- version 5.0.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : mer. 05 jan. 2022 à 14:20
-- Version du serveur :  10.4.14-MariaDB
-- Version de PHP : 7.4.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `blog`
--

-- --------------------------------------------------------

--
-- Structure de la table `article`
--

CREATE TABLE `article` (
  `id` int(11) UNSIGNED NOT NULL,
  `slug` varchar(255) NOT NULL,
  `lang` varchar(5) DEFAULT NULL,
  `title` varchar(150) NOT NULL,
  `text` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `article`
--

INSERT INTO `article` (`id`, `slug`, `lang`, `title`, `text`, `created_at`, `updated_at`) VALUES
(1, 'article-1', 'de', 'Artikel in Deutsch 1', 'Artikel in Deutsch. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(2, 'article-2', 'de', 'Artikel in Deutsch 2', 'Artikel in Deutsch. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(3, 'article-3', 'de', 'Artikel in Deutsch 3', 'Artikel in Deutsch. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(4, 'article-4', 'de', 'Artikel in Deutsch 4', 'Artikel in Deutsch. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(5, 'article-5', 'de', 'Artikel in Deutsch 5', 'Artikel in Deutsch. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(6, 'article-1', 'en', 'Article in English 1', 'Article in English. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(7, 'article-2', 'en', 'Article in English 2', 'Article in English. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(8, 'article-3', 'en', 'Article in English 3', 'Article in English. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(9, 'article-4', 'en', 'Article in English 4', 'Article in English. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(10, 'article-5', 'en', 'Article in English 5', 'Article in English. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(11, 'article-1', 'es', 'Artículo en español 1', 'Artículo en español. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(12, 'article-2', 'es', 'Artículo en español 2', 'Artículo en español. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(13, 'article-3', 'es', 'Artículo en español 3', 'Artículo en español. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(14, 'article-4', 'es', 'Artículo en español 4', 'Artículo en español. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(15, 'article-5', 'es', 'Artículo en español 5', 'Artículo en español. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(16, 'article-1', 'fr', 'Article en français 1', 'Article en français. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(17, 'article-2', 'fr', 'Article en français 2', 'Article en français. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(18, 'article-3', 'fr', 'Article en français 3', 'Article en français. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(19, 'article-4', 'fr', 'Article en français 4', 'Article en français. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(20, 'article-5', 'fr', 'Article en français 5', 'Article en français. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(21, 'article-1', 'ja', '日本語での記事 1', '日本語での記事. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(22, 'article-2', 'ja', '日本語での記事 2', '日本語での記事. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(23, 'article-3', 'ja', '日本語での記事 3', '日本語での記事. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(24, 'article-4', 'ja', '日本語での記事 4', '日本語での記事. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52'),
(25, 'article-5', 'ja', '日本語での記事 5', '日本語での記事. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nisi eros, ultrices vitae arcu fringilla, sollicitudin tempus lacus. Curabitur suscipit ex eu nisi volutpat, quis pharetra neque dictum. Sed commodo est blandit facilisis vehicula. Ut justo mauris, ultricies eu massa ac, dignissim porttitor ligula. Quisque nec magna ante. Nullam accumsan nunc sed accumsan ornare. Donec orci mi, lobortis sed purus quis, egestas viverra justo. Cras pulvinar, mauris ut efficitur venenatis, urna justo suscipit tortor, nec sodales lacus quam sed dui. Sed auctor, augue vel scelerisque molestie, ligula odio consequat ipsum, vel facilisis sapien velit non risus. Cras at molestie mauris. Nam a euismod purus. Cras vitae commodo orci, vel tempus tortor. Ut sodales, est ac volutpat congue, dui tortor luctus elit, sit amet accumsan lectus diam a tortor. Aenean convallis, elit vel scelerisque accumsan, enim nisi volutpat lacus, in interdum nulla elit nec nunc. Nullam eleifend elit cursus mauris elementum porta.\r\n\r\nNulla et dui at metus pretium accumsan sed et ligula. Integer sodales cursus elit in commodo. Suspendisse ultrices diam elit, sit amet fermentum dui vulputate sit amet. Aenean a eros nec arcu tempus consectetur id cursus quam. Cras quis arcu pellentesque, fringilla nisl vitae, accumsan elit. Praesent nec semper velit, a posuere diam. Quisque in arcu eros. Vivamus venenatis purus risus, ut vehicula turpis ullamcorper nec. Morbi purus leo, lobortis sollicitudin mi sit amet, blandit aliquet orci. Donec tincidunt consequat felis vitae bibendum. Ut porttitor ante eget dui volutpat venenatis. Mauris eget euismod neque, dapibus blandit eros. Cras condimentum metus ac mi tempor, in commodo orci vestibulum. Aliquam a ultricies leo. Integer quis auctor ligula. Nulla sed congue justo.', '2021-12-23 08:21:52', '2021-12-23 08:21:52');

-- --------------------------------------------------------

--
-- Structure de la table `migrations`
--

CREATE TABLE `migrations` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `version` varchar(255) NOT NULL,
  `class` varchar(255) NOT NULL,
  `group` varchar(255) NOT NULL,
  `namespace` varchar(255) NOT NULL,
  `time` int(11) NOT NULL,
  `batch` int(11) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `migrations`
--

INSERT INTO `migrations` (`id`, `version`, `class`, `group`, `namespace`, `time`, `batch`) VALUES
(1, '2021-12-23-130005', 'App\\Database\\Migrations\\CreateBlogTables', 'default', 'App', 1640269230, 1);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(55) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `password`) VALUES
(3, 'Ulrich Simon', 'simonulrich56@gmail.com', '$2y$10$0qnTUSirTAy87o07jS4dDOW7eAgismkcxyVwoBcIMVBeoTTZ/m8/K');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `article`
--
ALTER TABLE `article`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `article`
--
ALTER TABLE `article`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT pour la table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
